Enhancement #5 - Households and people at risk of food insecurity
NeighborhoodInfoDC/Covid19 pull request #6
Opened 2020-06-09 19:42 UTC by mcohenui

@NeighborhoodInfoDC/review Updated the original program Peter created to add variables for children, elders, and family type. Created a new file to create relevant tables.

2020-06-09 21:06 UTC, rpitingolo commented
Thanks @mcohenui 

Did you want to review this one @ptatian or should I go ahead?

2020-06-10 13:18 UTC, ptatian commented
Thanks, @rpitingolo and @mcohenui. I can review.

2020-06-11 23:00 UTC, ptatian requested changes
@mcohenui This looks good. You are on the right track. A few thoughts about how to make the tables a little cleaner and to include the person counts that they asked for. Let me know if you have questions. I can take another look when you have made changes.

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop_tables.sas
> -  weight perwt;
Not sure why you removed the weight statement here?

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +		else famtype = 5;
Famtype never equals 5 because the above conditions exhaust all of the possibilities.

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +        and hud_inc >= 1;
They wanted to see the lowest three income groups, so I would change this condition to `1 <= hud_inc <= 3`.

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +	numprec='\line \i By household size'
I'd suggest top-coding the household size variable by creating a format that maps 6+ person households to a single label. `6-high = '6+'`.

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +	hhtype='\line \i By household type'
Did you mean to use this variable or the famtype variable you created earlier?

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +    upuma,
For neatness, I'd suppress the variable label here: `upuma=' ',`

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +      n='N (unwtd)' * total=' ' * f=comma8.0
Seeing the unweighted N is helpful for making sure we aren't relying on too few cases for each table cell. But if we've reviewed and are satisfied with the size of the N's, then we could delete this column to make the table easier to read.

2020-06-11 23:00 UTC, ptatian commented on Prog/Cvd19_affctd_ind_pop.sas
> +  ;
I'd delete lines 543-556 and replace with the data on numbers of persons, children, and elders for the columns. You can modify the `sum=...` code starting on line 545 and replace the labels and variables with the appropriate ones.

2020-06-22 12:31 UTC, mcohenui commented
@ptatian I made the edits you requested to Cvd19_affctd_ind_pop.sas. I wasn't super clear on where I added the food insecurity tables. I made a separate program for that: Cvd19_affctd_ind_hh_foodinsecurity.sas

2020-06-22 13:41 UTC, ptatian commented
Thanks, @mcohenui. I'll try to look at this later today.

2020-06-23 21:42 UTC, ptatian commented
@mcohenui I've reviewed and your changes look good! You should be OK to merge this. I pushed a couple of small tweaks. I restored the style= option on the ODS statement because, without it, the tables won't come out properly. You just need to batch submit the program **L:\Libraries\General\Prog\Style_rtf_arial_9pt.sas** one time to create the style and then you should be good. 

Probably I should have set this up better to do the data set update one issue and then create the tables as a separate issue. That would have made it possible to debug the table code. Sorry if that was confusing.  But it looks to me like the new tables should run OK. If not, we can just create another issue to fix them. 

Let me know if you have any questions. 

cc: @rpitingolo

2020-06-23 21:43 UTC, ptatian approved these changes

2020-06-24 15:44 UTC, merged